final_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('user.urls', 'user'), namespace='user')),
    path('', include(('task.urls', 'task'), namespace='task')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('task/mine/', views.mytask, name='mytask'),
    path('task/create/', views.task_create, name='task_create'),
    path('task/detail/<int:task_id>/', views.task_detail, name='task_detail'),
    path('task/detail/<int:task_id>/applications/', views.task_application, name='task_application'),
    path('task/myapplication/', views.myapplication, name='myapplication'),
    path('task/available/', views.tasklist, name='tasklist'),
    path('task/ongoing/', views.task_ongoing, name='task_ongoing'),
    path('task/apply/<int:task_id>/', views.task_apply, name='task_apply'),
    path('task/application/<int:application_id>/approve/', views.approve_application, name='approve_application'),
    path('task/application/<int:application_id>/reject/', views.reject_application, name='reject_application'),
    path('cancel/<int:task_id>/', views.cancel_task, name='cancel_task'),
]

task/models.py
from django.db import models
from django.conf import settings
from user.models import CustomUser, UserProfile, ClientProfile, VolunteerProfile, SupportType
from django.utils import timezone

# Create your models here.
class Task(models.Model):
    STATUS_CHOICES = [
        ('open', 'Open for application'),
        ('selected', 'Selecting Done'),
        ('ongoing', 'Ongoing'),
        ('completed', 'Completed'),
        ('cancelled', 'Cancelled'),
    ]

    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    work_area = models.ManyToManyField(SupportType)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    vol_number = models.PositiveIntegerField()
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='open')
    client = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='posted_tasks')
    created_at = models.DateTimeField(auto_now_add=True)
    closed_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.title} ({self.client.email})"
    
    def update_status_if_full(self):
        if self.status == 'cancelled':
            return
        approved_count = self.applications.filter(status='accepted').count()
        if approved_count >= self.vol_number and self.status != 'selected':
            self.status = 'selected'
            self.save()

    def update_status_by_time(self):
        """根据时间更新任务状态"""
        now = timezone.now()
        if self.status == 'cancelled':
            return
        if now > self.end_time:
            self.status = 'completed'
            self.closed_at = now
        elif now >= self.start_time and now <= self.end_time:
            self.status = 'ongoing'
        elif now < self.start_time and self.status != 'selected':
            self.status = 'open'
        self.save()
        
    def cancel(self):
        self.status = 'cancelled'
        self.closed_at = timezone.now()
        self.save()
        self.applications.update(status='cancelled')

    @property
    def is_active(self):
        return self.status in ['open', 'selected']
    
    @property
    def is_closed(self):
        return self.status in ['completed', 'cancelled']
    
    @property
    def is_ongoing(self):
        return self.status in ['ongoing']
    

class TaskApplication(models.Model):
    STATUS_CHOICES = [
        ('pending', 'pending'),
        ('accepted', 'accepted'),
        ('unselected', 'unselected'),
        ('rejected', 'rejected'),
        ('cancelled', 'cancelled'),
    ]

    task = models.ForeignKey('Task', on_delete=models.CASCADE, related_name='applications')
    volunteer = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='applications')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending')
    applied_at = models.DateTimeField(auto_now_add=True)
    cancelled_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        unique_together = ('task', 'volunteer')  # 每个志愿者只能申请一次

    def __str__(self):
        return f"{self.volunteer.email}applys for {self.task.title}"
    
    def cancel(self):
        self.status = 'cancelled'
        self.cancelled_at = timezone.now()
        self.save()

task/forms.py
from django import forms
from .models import Task
from user.models import SupportType

class TaskForm(forms.ModelForm):
    vol_number = forms.IntegerField(min_value=1)
    work_area = forms.ModelMultipleChoiceField(
        queryset=SupportType.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        label='Needed Work Areas'
    )
    class Meta:
        model = Task
        fields = ['title', 'description', 'start_time', 'end_time', 'vol_number', 'work_area']
        widgets = {
            'start_time': forms.TextInput(attrs={'id': 'start_time'}),
            'end_time': forms.TextInput(attrs={'id': 'end_time'}),
        }

task/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import TaskForm
from django.http import HttpResponseForbidden
from functools import wraps
from .models import Task, TaskApplication
from django.utils import timezone
from datetime import timedelta

# Create your views here.
def client_required(view_func):
    @wraps(view_func)
    def _wrapped_view(request, *args, **kwargs):
        if request.user.role != 'client':
            return HttpResponseForbidden("You do not have permission to access this page")
        return view_func(request, *args, **kwargs)
    return _wrapped_view

def volunteer_required(view_func):
    @wraps(view_func)
    def _wrapped_view(request, *args, **kwargs):
        if request.user.role != 'volunteer':
            return HttpResponseForbidden("You do not have permission to access this page")
        return view_func(request, *args, **kwargs)
    return _wrapped_view

@login_required
@client_required
def mytask(request):
    tasks = Task.objects.filter(client=request.user).order_by('-start_time')
    for task in tasks:
        task.update_status_if_full()
        task.update_status_by_time()
    return render(request, 'task/mytask.html', {'tasks': tasks})

@login_required
@client_required
def task_create(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.client = request.user
            task.status = 'open'
            task.save()
            return redirect('task:mytask')
    else:
        form = TaskForm()

    return render(request, 'task/task_create.html', {'form': form})

@login_required
def task_detail(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    task.update_status_by_time()
    user = request.user

    is_client = (user == task.client)

    has_applied = False
    application_status = None
    if hasattr(user, 'volunteerprofile'):
        application = TaskApplication.objects.filter(task=task, volunteer=user).first()
        if application:
            has_applied = True
            application_status = application.status

    context = {
        'task': task,
        'is_client': is_client,
        'has_applied': has_applied,
        'application_status': application_status,
    }
    return render(request, 'task/task_detail.html', context)

@login_required
@client_required
def task_application(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    task.update_status_by_time()
    applications = TaskApplication.objects.filter(task=task).select_related('volunteer')
    context = {
        'task': task,
        'applications': applications,
    }
    return render(request, 'task/task_application.html', context)

@login_required
@volunteer_required
def myapplication(request):
    user = request.user
    applications = TaskApplication.objects.filter(volunteer=user).select_related('task').order_by('-applied_at')
    return render(request, 'task/myapplication.html', {'applications': applications})

@login_required
@volunteer_required
def tasklist(request):
    user = request.user
    applied_task_ids = TaskApplication.objects.filter(volunteer=user).values_list('task_id', flat=True)
    tasks = Task.objects.filter(status='open').exclude(id__in=applied_task_ids)
    for task in tasks:
        task.update_status_by_time()
    return render(request, 'task/tasklist.html', {'tasks': tasks})

@login_required
def task_ongoing(request):
    user = request.user
    if user.role == 'client':
        tasks = Task.objects.filter(client=user, status='ongoing')
    else:
        tasks = Task.objects.filter(applications__volunteer=user, applications__status='accepted', status='ongoing')
    for task in tasks:
        task.update_status_by_time()
    tasks_with_status = []
    for task in tasks:
        has_accepted_application = (user.role == 'volunteer' and 
                                  task.applications.filter(volunteer=user, status='accepted').exists())
        tasks_with_status.append({
            'task': task,
            'has_accepted_application': has_accepted_application
        })
    
    return render(request, 'task/task_ongoing.html', {
        'tasks_with_status': tasks_with_status,
        'user': user
    })

@login_required
@volunteer_required
def task_apply(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    task.update_status_by_time()
    user = request.user

    buffer = timedelta(hours=1)  # 任务前后一小时不能有其他任务，不确定，可以再改
    task_start = task.start_time - buffer
    task_end = task.end_time + buffer

    conflicting_apps = TaskApplication.objects.filter(
        volunteer=user,
        status__in=['pending', 'accepted'],
        task__start_time__lt=task_end,
        task__end_time__gt=task_start
    )
    if conflicting_apps.exists():
        messages.error(request, "You have another task near this time. Please check your schedule.")
        return redirect('task:task_detail', task_id=task.id)

    if TaskApplication.objects.filter(task=task, volunteer=request.user).exists():
        messages.warning(request, "You have already applied for the task")
    else:
        TaskApplication.objects.create(task=task, volunteer=request.user, status='pending')
        messages.success(request, "Application successful, please wait for review")

    return redirect('task:task_detail', task_id=task.id)

@login_required
@client_required
def approve_application(request, application_id):
    application = get_object_or_404(TaskApplication, id=application_id)
    task = application.task
    task.update_status_by_time()

    if application.status != 'pending':
        return redirect('task:task_application', task.id)
    
    approved_count = TaskApplication.objects.filter(task=task, status='accepted').count()
    if approved_count >= task.vol_number:
        return redirect('task:task_application', task.id)
    
    application.status = 'accepted'
    application.save()

    if approved_count + 1 >= task.vol_number:
        TaskApplication.objects.filter(task=task, status='pending').update(status='unselected')
        task.status = 'selected'
        task.save()
    return redirect('task:task_application', task.id)

@login_required
@client_required
def reject_application(request, application_id):
    application = get_object_or_404(TaskApplication, id=application_id)
    task = application.task
    task.update_status_by_time()
    if application.status != 'pending':
        return redirect('task:task_application', task.id)
    
    application.status = 'rejected'
    application.save()
    return redirect('task:task_application', task.id)

@login_required
@client_required
def cancel_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    task.update_status_by_time()
    
    if request.method == 'POST':
        task.cancel()
        return redirect('task:mytask')

    return redirect('task:task_detail', task_id=task.id)

@login_required
@volunteer_required
def cancel_application(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    task.update_status_by_time()
    user = request.user
    application = TaskApplication.objects.filter(task=task, volunteer=user).first()

    if request.method == 'POST':
        application.cancel()
        return redirect('task:myapplication')
    
    return redirect('task:task_detail', task_id=task.id)

task/templates/task/myapplication.html
{% extends "base.html" %}

{% block title %}My Application{% endblock %}

{% block content %}
    <div style='margin:50px;'>
        <p>这里展示用户的全部申请</p>
        {% if applications %}
            {% for application in applications %}
                <a href="{% url 'task:task_detail' application.task.id %}">{{ application.task.title }}</a><br>
                — Time: {{ application.task.start_time }} to {{ application.task.end_time }}<br>
                — Status: {{ application.status }}<br>
            {% endfor %}
        {% else %}
            <p>There is no any applications</p>
        {% endif %}
        <p><a href="{% url 'task:tasklist' %}">Go to the task list to find a new task</a></p>
    </div>
{% endblock %}

task/templates/task/mytask.html
{% extends "base.html" %}

{% block title %}My Task{% endblock %}

{% block content %}
    <div style='margin:50px;'>
        <h2>My Tasks</h2>
        {% if tasks %}
            <h3>Active Tasks</h3>
            {% for task in tasks %}
                {% if task.is_active %}    
                    <a href="{% url 'task:task_detail' task.id %}">{{ task.title }}</a><br>
                    — Status: [{{ task.status }}]<br>
                    — Time: [{{ task.start_time }}] to [{{ task.end_time }}]<br>
                    — Volunteer needed: [{{ task.vol_number }}]<br>
                {% endif %}
            {% endfor %}
            <h3>Closed Tasks</h3>
            {% for task in tasks %}
                {% if task.is_closed %}
                    <a href="{% url 'task:task_detail' task.id %}">{{ task.title }}</a><br>
                    — Status: [{{ task.status }}]<br>
                    — Time: [{{ task.start_time }}] to [{{ task.end_time }}]<br>
                    — Volunteer needed: [{{ task.vol_number }}]<br>
                {% endif %}
            {% endfor %}

        {% else %}
            <p>You haven't posted any tasks yet.</p>
        {% endif %}
        <p><a href="{% url 'task:task_create' %}">Create a new task</a></p>
    </div>
{% endblock %}

task/templates/task/task_application.html
{% extends "base.html" %}

{% block title %}Applications{% endblock %}

{% block content %}
    <div style='margin:50px;'>
        <h2>Applications</h2>
        <p>Needed Volunteer Number: {{ task.vol_number }}</p>
        {% if applications %}
            <ul>
                {% for app in applications %}
                    <li>
                        Volunteer: {{ app.volunteer.userprofile.first_name }} {{ app.volunteer.userprofile.last_name }}
                        — Status: {{ app.status }}

                        {% if app.status == 'pending' %}
                        <form method="post" action="{% url 'task:approve_application' app.id %}" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit">Approve</button>
                        </form>
                        <form method="post" action="{% url 'task:reject_application' app.id %}" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit">Reject</button>
                        </form>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No volunteers have applied for this task now.</p>
        {% endif %}
        
    </div>
{% endblock %}

task/templates/task/task_create.html
{% extends "base.html" %}

{% block title %}Create a new task{% endblock %}

{% block content %}
    <div style='margin:50px;'>
        <p>用户在这里创建新的任务，考虑给任务内容加图，以及预制几个基本任务</p>
        <h2>Create a new task</h2>
        <form method="post" id="task-form">
            {% csrf_token %}

            <label for="id_title"><strong>1. Please enter the task title:</strong></label><br>
            {{ form.title }}<br>
            {{ form.title.errors }}<br><br>

            <label for="id_description"><strong>2. Please enter the task description:</strong></label><br>
            {{ form.description }}<br>
            {{ form.description.errors }}<br><br>

            <label for="id_start_time"><strong>3. Please choose the start time:</strong></label><br>
            {{ form.start_time }}<br>
            {{ form.start_time.errors }}<br><br>

            <label for="id_end_time"><strong>4. Please choose the end time:</strong></label><br>
            {{ form.end_time }}<br>
            <span>Please note that the period of time needs to be between half an hour and four hours.</span><br>
            {{ form.end_time.errors }}<br><br>

            <label for="id_vol_number"><strong>5. Please choose the needed volunteer number:</strong></label><br>
            {{ form.vol_number }}<br>
            {{ form.vol_number.errors }}<br><br>

            <label for="id_work_area"><strong>6. Please choose the needed support:</strong></label><br>
            {{ form.work_area }}<br>
            {{ form.work_area.errors }}<br><br>


            {% comment %} {{ form.as_p }} {% endcomment %}
            <button type="submit">Post</button>
        </form>
    </div>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script>
    document.addEventListener('DOMContentLoaded', function () {
        const startInput = document.getElementById('start_time');
        const endInput = document.getElementById('end_time');

        const endPicker = flatpickr(endInput, {
            enableTime: true,
            time_24hr: true,
            dateFormat: "Y-m-d\\TH:i",
            minuteIncrement: 5,
        });

        const startPicker = flatpickr(startInput, {
            enableTime: true,
            time_24hr: true,
            dateFormat: "Y-m-d\\TH:i",
            minuteIncrement: 5,
            onChange: function(selectedDates, dateStr) {
                if (selectedDates.length === 0) return;

                const start = selectedDates[0];
                const minEnd = new Date(start.getTime() + 30 * 60 * 1000);
                const maxEnd = new Date(start.getTime() + 4 * 60 * 60 * 1000);

                endPicker.set('minDate', minEnd);
                endPicker.set('maxDate', maxEnd);
                endPicker.setDate(minEnd, true);
            }
        });
    });
    </script>
{% endblock %}

task/templates/task/task_detail.html
{% extends "base.html" %}

{% block title %}Task Detail{% endblock %}

{% block content %}
    <div style='margin:50px;'>
        <p>任务详情，病人和志愿者会看到不同的按钮</p>
        <h2>{{ task.title }}</h2>
        <p>{{ task.description }}</p>
        <p>Time: {{ task.start_time }} - {{ task.end_time }}</p>
        <p>Volunteer needed: {{ task.vol_number }}</p>
        <p>Status: {{ task.status }}</p>
        <p>Created at: {{ task.created_at }}</p>
        {% if task.is_active %}
            {% if is_client %}     
                    <a href="{% url 'task:task_application' task.id %}">View applied volunteers</a>
                
                    <form method="post" action="{% url 'task:cancel_task' task.id %}" style="margin-top:10px;">
                        {% csrf_token %}
                        <button type="submit" onclick="return confirm('Are you sure you want to cancel this task?');">Cancel This Task</button>
                    </form>
            {% elif has_applied %}
                <p>You have applied. Application status:{{ application_status }}</p>
                <form method="post" action="{% url 'task:cancel_application' task.id %}" style="margin-top:10px;">
                    {% csrf_token %}
                    <button type="submit" onclick="return confirm('Are you sure you want to cancel this application?');">Cancel This Application</button>
                </form>
            {% else %}
                <form method="post" action="{% url 'task:task_apply' task.id %}">
                    {% csrf_token %}
                    <button type="submit">Application for this task</button>
                </form>
                <p>Notice: You can't apply for time-conflicting tasks. Please leave at least one hour between tasks.</p>
            {% endif %}
        {% elif task.is_closed %}
            <p>Closed at: {{ task.closed_at }}
        {% endif %}
    </div>
{% endblock %}

task/templates/task/task_ongoing.html
{% extends 'base.html' %}
{% block content %}
  <h2>Ongoing Tasks</h2>
  {% if tasks_with_status %}
    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Start Time</th>
          <th>End Time</th>
          <th>Status</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for item in tasks_with_status %}
          <tr>
            <td>{{ item.task.title }}</td>
            <td>{{ item.task.start_time|date:"Y-m-d H:i" }}</td>
            <td>{{ item.task.end_time|date:"Y-m-d H:i" }}</td>
            <td>{{ item.task.get_status_display }}</td>
            <td>
              <a href="{% url 'task:task_detail' item.task.id %}" class="btn btn-info">View Details</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>No ongoing tasks found for this user.</p>
  {% endif %}
{% endblock %}

task/templates/task/tasklist.html
{% extends "base.html" %}

{% block title %}Task List{% endblock %}

{% block content %}
    <div style='margin:50px;'>
        <p>这里展示全部的可用任务，提供过滤器进行筛选</p>
        {% if tasks %}
            {% for task in tasks %}
                <a href="{% url 'task:task_detail' task.id %}">{{ task.title }}</a><br>
                Time: {{ task.start_time }} to {{ task.end_time }}<br>
                Volunteer Number: {{ task.vol_number }}
            {% endfor %}
        {% else %}
            <p>There are currently no tasks available for application.</p>
        {% endif %}
    </div>
{% endblock %}